let ALL=[],CATS={},cat='all',query='',sort='quality',visible=48;const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
async function init(){try{ALL=await(await fetch('data/games.json')).json();CATS=await(await fetch('data/categories.json')).json()}catch(e){console.error(e);return}build();renderSections();render();bind()}
function build(){let es=Object.entries(CATS).sort((a,b)=>b[1]-a[1]);$('#catStrip').innerHTML='<button class="cat-pill active" data-cat="all">All</button>'+es.slice(0,22).map(x=>`<button class="cat-pill" data-cat="${esc(x[0])}">${esc(cap(x[0]))}</button>`).join('');$('#sideCategories').innerHTML=es.map(x=>`<button class="side-link" data-cat="${esc(x[0])}" onclick="selectCategory('${jsq(x[0])}')">🎮 <span>${esc(cap(x[0]))}</span></button>`).join('');$('#catStrip').onclick=e=>{let b=e.target.closest('[data-cat]');if(b)selectCategory(b.dataset.cat)}}
function bind(){$('#searchInput').oninput=e=>{query=e.target.value.trim().toLowerCase();$('#clearSearch').classList.toggle('show',!!query);visible=48;render()};$('#clearSearch').onclick=()=>{$('#searchInput').value='';query='';$('#clearSearch').classList.remove('show');render()};$('#sortSelect').onchange=e=>{sort=e.target.value;visible=48;render()};$('#loadMoreBtn').onclick=()=>{visible+=48;render()};$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#mobileSearch').onclick=()=>$('.search-wrap').classList.toggle('mobile-open')}
function selectCategory(x){cat=x;query='';$('#searchInput').value='';visible=48;$$('.cat-pill').forEach(b=>b.classList.toggle('active',b.dataset.cat===x));$$('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.cat===x));render();jumpSection('all-games')}
function setSpecial(t){cat='all';sort=t==='new'?'new':'quality';$('#sortSelect').value=sort;render();jumpSection('all-games')}
function list(){let a=ALL.filter(g=>cat==='all'||g.category===cat);if(query)a=a.filter(g=>(g.title||'').toLowerCase().includes(query)||(g.category||'').toLowerCase().includes(query));if(sort==='az')a.sort((x,y)=>x.title.localeCompare(y.title));else if(sort==='za')a.sort((x,y)=>y.title.localeCompare(x.title));else if(sort==='new')a.sort((x,y)=>new Date(y.date_published||0)-new Date(x.date_published||0));else a.sort((x,y)=>Number(y.quality_score||0)-Number(x.quality_score||0));return a}
function render(){let a=list();$('#sectionTitle').textContent=query?`Results for "${$('#searchInput').value}"`:cat==='all'?'All Games':cap(cat)+' Games';$('#sectionSubtitle').textContent=a.length.toLocaleString()+' games';$('#gamesGrid').innerHTML=a.slice(0,visible).map(card).join('');$('#emptyState').hidden=!!a.length;$('#loadMoreBtn').hidden=visible>=a.length}
function renderSections(){let p=[...ALL].sort((a,b)=>Number(b.quality_score||0)-Number(a.quality_score||0)).slice(0,6),n=[...ALL].sort((a,b)=>new Date(b.date_published||0)-new Date(a.date_published||0)).slice(0,6);$('#popularGrid').innerHTML=p.map(card).join('');$('#newGrid').innerHTML=n.map(card).join('')}
function card(g){let ns=g.namespace||slug(g.title);return `<article class="game-card" onclick="openGame('${jsq(ns)}')"><div class="thumb"><img src="${esc(g.image||g.banner_image)}" alt="${esc(g.title)}" loading="lazy" onerror="this.src='${esc(g.banner_image)}'"><div class="play-overlay"><span>▶</span></div></div><div class="game-info"><p class="game-title">${esc(g.title)}</p><div class="game-cat">${esc(cap(g.category))}</div></div></article>`}
function openGame(ns){let a=JSON.parse(localStorage.getItem('gameburst_recent')||'[]');a=[ns,...a.filter(x=>x!==ns)].slice(0,12);localStorage.setItem('gameburst_recent',JSON.stringify(a));location.href='games/'+encodeURIComponent(ns)+'/'}
function showRecent(){let a=JSON.parse(localStorage.getItem('gameburst_recent')||'[]').map(ns=>ALL.find(g=>(g.namespace||slug(g.title))===ns)).filter(Boolean);$('#sectionTitle').textContent='Recently Played';$('#sectionSubtitle').textContent=a.length+' games';$('#gamesGrid').innerHTML=a.map(card).join('');$('#loadMoreBtn').hidden=true;jumpSection('all-games')}
function jumpSection(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}function resetHome(){cat='all';query='';sort='quality';visible=48;$('#searchInput').value='';renderSections();render();window.scrollTo({top:0,behavior:'smooth'})}function cap(s){return String(s||'').replace(/[-_]+/g,' ').replace(/\b\w/g,x=>x.toUpperCase())}function slug(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}function esc(s){let d=document.createElement('div');d.textContent=s??'';return d.innerHTML}function jsq(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}init();