'use strict';
const calculators = [
{id:'basic',title:'Basic Calculator',formula:'a + b',example:'12 + 8 = 20',tips:'Use positive or negative values as needed',category:'Math',icon:'➗',description:'Perform addition, subtraction, multiplication, and division.',fields:[['a','First number','number'],['b','Second number','number']],run:v=>({value:v.a+v.b,detail:'This starter tool adds the two entered numbers.'})},
{id:'percentage',title:'Percentage Calculator',category:'Math',icon:'％',description:'Find a percentage of a number.',fields:[['percent','Percentage','number'],['number','Number','number']],run:v=>({value:v.percent/100*v.number,detail:`${v.percent}% of ${v.number}`})},
{id:'percent-change',title:'Percentage Change',category:'Math',icon:'↗',description:'Calculate the percentage change between two values.',fields:[['old','Original value','number'],['newValue','New value','number']],run:v=>{if(v.old===0)throw Error('Original value must not be zero.');return{value:(v.newValue-v.old)/Math.abs(v.old)*100,unit:'%',detail:'Positive means an increase; negative means a decrease.'}}},
{id:'average',title:'Average Calculator',category:'Math',icon:'∑',description:'Calculate the arithmetic mean of a list of numbers.',fields:[['numbers','Numbers separated by commas','text']],run:v=>{const a=v.numbers.split(',').map(Number);if(!a.length||a.some(Number.isNaN))throw Error('Enter valid comma-separated numbers.');return{value:a.reduce((x,y)=>x+y,0)/a.length,detail:`Based on ${a.length} values.`}}},
{id:'ratio',title:'Ratio Calculator',category:'Math',icon:'∶',description:'Simplify a ratio of two positive numbers.',fields:[['a','First part','number'],['b','Second part','number']],run:v=>{if(v.a<=0||v.b<=0)throw Error('Both values must be greater than zero.');const g=(x,y)=>y?g(y,x%y):x;const d=g(Math.round(v.a),Math.round(v.b));return{value:`${v.a/d} : ${v.b/d}`,detail:'Simplified using the greatest common divisor.'}}},
{id:'square-root',title:'Square Root',category:'Math',icon:'√',description:'Find the square root of a non-negative number.',fields:[['number','Number','number']],run:v=>{if(v.number<0)throw Error('Enter a non-negative number.');return{value:Math.sqrt(v.number)}}},
{id:'power',title:'Exponent Calculator',category:'Math',icon:'xʸ',description:'Raise a base number to a chosen exponent.',fields:[['base','Base','number'],['exponent','Exponent','number']],run:v=>({value:Math.pow(v.base,v.exponent)})},
{id:'simple-interest',title:'Simple Interest',category:'Finance',icon:'$',description:'Estimate simple interest using principal, rate, and time.',fields:[['principal','Principal','number'],['rate','Annual rate (%)','number'],['years','Time (years)','number']],run:v=>({value:v.principal*v.rate/100*v.years,detail:'Interest only; principal is not included.'})},
{id:'compound-interest',title:'Compound Interest',category:'Finance',icon:'📈',description:'Estimate growth with compound interest.',fields:[['principal','Starting principal','number'],['rate','Annual rate (%)','number'],['years','Years','number'],['frequency','Compounds per year','number']],run:v=>{if(v.frequency<=0)throw Error('Compounds per year must be positive.');return{value:v.principal*Math.pow(1+v.rate/100/v.frequency,v.frequency*v.years)-v.principal,detail:'Interest earned, excluding the starting principal.'}}},
{id:'loan-payment',title:'Loan Payment',category:'Finance',icon:'🏦',description:'Estimate a fixed monthly loan payment.',fields:[['principal','Loan amount','number'],['rate','Annual interest rate (%)','number'],['months','Term (months)','number']],run:v=>{if(v.months<=0)throw Error('Term must be positive.');const r=v.rate/1200;const p=r===0?v.principal/v.months:v.principal*r/(1-Math.pow(1+r,-v.months));return{value:p,detail:'Estimated monthly principal-and-interest payment; fees and taxes excluded.'}}},
{id:'bmi',title:'BMI Calculator',category:'Health',icon:'⚖',description:'Calculate body mass index from weight and height.',fields:[['weight','Weight (kg)','number'],['height','Height (cm)','number']],run:v=>{if(v.weight<=0||v.height<=0)throw Error('Weight and height must be positive.');return{value:v.weight/Math.pow(v.height/100,2),detail:'BMI is a screening measure, not a diagnosis.'}}},
{id:'bmr',title:'BMR Calculator',category:'Health',icon:'🔥',description:'Estimate basal metabolic rate using the Mifflin-St Jeor equation.',fields:[['weight','Weight (kg)','number'],['height','Height (cm)','number'],['age','Age (years)','number'],['sex','Sex: male or female','text']],run:v=>{const s=v.sex.trim().toLowerCase();if(!['male','female'].includes(s))throw Error('Enter male or female.');return{value:10*v.weight+6.25*v.height-5*v.age+(s==='male'?5:-161),unit:' kcal/day',detail:'Estimate using Mifflin-St Jeor; individual needs vary.'}}},
{id:'age',title:'Age Calculator',category:'Time & Date',icon:'🎂',description:'Calculate age in completed years from a birth date.',fields:[['birth','Birth date','date']],run:v=>{const b=new Date(v.birth+'T00:00:00');const now=new Date();if(Number.isNaN(b.getTime())||b>now)throw Error('Enter a valid past date.');let age=now.getFullYear()-b.getFullYear();const before=now.getMonth()<b.getMonth()||(now.getMonth()===b.getMonth()&&now.getDate()<b.getDate());if(before)age--;return{value:age,unit:' years'}}},
{id:'days-between',title:'Days Between Dates',category:'Time & Date',icon:'📅',description:'Find the number of days between two dates.',fields:[['start','Start date','date'],['end','End date','date']],run:v=>{const a=new Date(v.start+'T00:00:00'),b=new Date(v.end+'T00:00:00');if(Number.isNaN(a.getTime())||Number.isNaN(b.getTime()))throw Error('Enter both dates.');return{value:Math.round((b-a)/86400000),unit:' days',detail:'End date minus start date; the starting date is not counted as a full day.'}}},
{id:'speed',title:'Speed Calculator',category:'Science',icon:'⚡',description:'Calculate speed from distance and time.',fields:[['distance','Distance','number'],['time','Time','number']],run:v=>{if(v.time<=0)throw Error('Time must be positive.');return{value:v.distance/v.time,detail:'Distance units per time unit.'}}},
{id:'distance',title:'Distance Calculator',category:'Science',icon:'↔',description:'Calculate distance from speed and time.',fields:[['speed','Speed','number'],['time','Time','number']],run:v=>({value:v.speed*v.time})},
{id:'rectangle-area',title:'Rectangle Area',category:'Geometry',icon:'▭',description:'Calculate the area of a rectangle.',fields:[['length','Length','number'],['width','Width','number']],run:v=>({value:v.length*v.width,unit:' square units'})},
{id:'triangle-area',title:'Triangle Area',category:'Geometry',icon:'△',description:'Calculate triangle area from base and height.',fields:[['base','Base','number'],['height','Height','number']],run:v=>({value:.5*v.base*v.height,unit:' square units'})},
{id:'circle-area',title:'Circle Area',category:'Geometry',icon:'◯',description:'Calculate the area of a circle from its radius.',fields:[['radius','Radius','number']],run:v=>{if(v.radius<0)throw Error('Radius cannot be negative.');return{value:Math.PI*v.radius*v.radius,unit:' square units'}}},
{id:'circle-circumference',title:'Circle Circumference',category:'Geometry',icon:'◉',description:'Calculate the circumference of a circle.',fields:[['radius','Radius','number']],run:v=>{if(v.radius<0)throw Error('Radius cannot be negative.');return{value:2*Math.PI*v.radius,unit:' units'}}},
{id:'volume-box',title:'Box Volume',category:'Geometry',icon:'▣',description:'Calculate volume from length, width, and height.',fields:[['length','Length','number'],['width','Width','number'],['height','Height','number']],run:v=>({value:v.length*v.width*v.height,unit:' cubic units'})},
{id:'temperature',title:'Celsius to Fahrenheit',category:'Conversion',icon:'🌡',description:'Convert Celsius temperature to Fahrenheit.',fields:[['celsius','Temperature (°C)','number']],run:v=>({value:v.celsius*9/5+32,unit:' °F'})},
{id:'kilometers-miles',title:'Kilometers to Miles',category:'Conversion',icon:'🛣',description:'Convert kilometers into miles.',fields:[['km','Kilometers','number']],run:v=>({value:v.km*.621371,unit:' miles'})},
{id:'meters-feet',title:'Meters to Feet',category:'Conversion',icon:'📏',description:'Convert meters into feet.',fields:[['meters','Meters','number']],run:v=>({value:v.meters*3.280839895,unit:' feet'})},
{id:'hours-minutes',title:'Hours to Minutes',category:'Conversion',icon:'⏱',description:'Convert hours into minutes.',fields:[['hours','Hours','number']],run:v=>({value:v.hours*60,unit:' minutes'})},
{id:'discount',title:'Discount Calculator',category:'Finance',icon:'🏷',description:'Calculate discount amount and final price.',fields:[['price','Original price','number'],['discount','Discount (%)','number']],run:v=>{const saved=v.price*v.discount/100;return{value:v.price-saved,detail:`You save ${saved.toFixed(2)} (${v.discount}%).`}}}
,{id:'fraction-simplifier',title:'Fraction Simplifier',category:'Math',icon:'½',description:'Reduce a fraction to its simplest form.',fields:[['numerator','Numerator','number'],['denominator','Denominator','number']],run:v=>{if(!Number.isInteger(v.numerator)||!Number.isInteger(v.denominator)||v.denominator===0)throw Error('Use integers and a non-zero denominator.');const g=(a,b)=>b?g(b,a%b):Math.abs(a);const d=g(v.numerator,v.denominator);return{value:`${v.numerator/d}/${v.denominator/d}`,detail:'Fraction reduced by the greatest common divisor.'}}}
,{id:'perimeter-rectangle',title:'Rectangle Perimeter',category:'Geometry',icon:'▱',description:'Calculate the perimeter of a rectangle.',fields:[['length','Length','number'],['width','Width','number']],run:v=>{if(v.length<0||v.width<0)throw Error('Dimensions cannot be negative.');return{value:2*(v.length+v.width),unit:' units'}}}
,{id:'pythagorean',title:'Pythagorean Theorem',category:'Geometry',icon:'📐',description:'Find the hypotenuse of a right triangle.',fields:[['a','Leg A','number'],['b','Leg B','number']],run:v=>{if(v.a<=0||v.b<=0)throw Error('Both legs must be positive.');return{value:Math.hypot(v.a,v.b),unit:' units'}}}
,{id:'body-surface-area',title:'Body Surface Area',category:'Health',icon:'🩺',description:'Estimate body surface area using the Mosteller formula.',fields:[['weight','Weight (kg)','number'],['height','Height (cm)','number']],run:v=>{if(v.weight<=0||v.height<=0)throw Error('Weight and height must be positive.');return{value:Math.sqrt(v.weight*v.height/3600),unit:' m²',detail:'Mosteller estimate; not a clinical prescription.'}}}
,{id:'calorie-deficit',title:'Calorie Deficit',category:'Health',icon:'🔥',description:'Calculate the difference between maintenance calories and intake.',fields:[['maintenance','Maintenance calories','number'],['intake','Daily intake','number']],run:v=>({value:v.maintenance-v.intake,unit:' kcal/day',detail:'Positive values indicate intake below maintenance.'})}
,{id:'markup',title:'Markup Calculator',category:'Finance',icon:'📊',description:'Calculate selling price from cost and markup percentage.',fields:[['cost','Cost','number'],['markup','Markup (%)','number']],run:v=>({value:v.cost*(1+v.markup/100),detail:`Markup amount: ${(v.cost*v.markup/100).toFixed(2)}`})}
,{id:'sales-tax',title:'Sales Tax Calculator',category:'Finance',icon:'🧾',description:'Calculate total price after sales tax.',fields:[['price','Price before tax','number'],['tax','Tax rate (%)','number']],run:v=>({value:v.price*(1+v.tax/100),detail:`Tax amount: ${(v.price*v.tax/100).toFixed(2)}`})}
,{id:'fuel-cost',title:'Fuel Cost Calculator',category:'Everyday',icon:'⛽',description:'Estimate trip fuel cost from distance, efficiency, and fuel price.',fields:[['distance','Distance (km)','number'],['efficiency','Efficiency (km/L)','number'],['price','Fuel price per liter','number']],run:v=>{if(v.distance<0||v.efficiency<=0||v.price<0)throw Error('Use valid non-negative values and positive efficiency.');return{value:v.distance/v.efficiency*v.price,detail:`Estimated fuel used: ${(v.distance/v.efficiency).toFixed(2)} L`}}}
,{id:'unit-price',title:'Unit Price Calculator',category:'Everyday',icon:'🏷',description:'Find the price per unit from total price and quantity.',fields:[['price','Total price','number'],['quantity','Quantity','number']],run:v=>{if(v.quantity<=0)throw Error('Quantity must be positive.');return{value:v.price/v.quantity,unit:' per unit'}}}
,{id:'tip',title:'Tip Calculator',category:'Everyday',icon:'💵',description:'Calculate a tip and total bill amount.',fields:[['bill','Bill amount','number'],['rate','Tip rate (%)','number'],['people','Number of people','number']],run:v=>{if(v.people<=0)throw Error('People must be positive.');const tip=v.bill*v.rate/100;return{value:(v.bill+tip)/v.people,detail:`Total with tip: ${(v.bill+tip).toFixed(2)}; per person.`}}}


,{id:'gcd',title:'GCD Calculator',category:'Math',icon:'∴',description:'Find the greatest common divisor of two integers.',fields:[['a','First integer','number'],['b','Second integer','number']],run:v=>{if(!Number.isInteger(v.a)||!Number.isInteger(v.b)||v.a===0&&v.b===0)throw Error('Enter integers; at least one must be non-zero.');let a=Math.abs(v.a),b=Math.abs(v.b);while(b){const t=b;b=a%b;a=t}return{value:a,detail:'Greatest common divisor of the two integers.'}}}
,{id:'lcm',title:'LCM Calculator',category:'Math',icon:'↔',description:'Find the least common multiple of two integers.',fields:[['a','First integer','number'],['b','Second integer','number']],run:v=>{if(!Number.isInteger(v.a)||!Number.isInteger(v.b)||v.a===0||v.b===0)throw Error('Enter non-zero integers.');const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){const t=b;b=a%b;a=t}return a};return{value:Math.abs(v.a*v.b)/gcd(v.a,v.b),detail:'Least positive common multiple.'}}}
,{id:'quadratic-roots',title:'Quadratic Equation Solver',category:'Math',icon:'x²',description:'Solve ax² + bx + c = 0 for real roots.',fields:[['a','Coefficient a','number'],['b','Coefficient b','number'],['c','Coefficient c','number']],run:v=>{if(v.a===0)throw Error('Coefficient a must not be zero.');const d=v.b*v.b-4*v.a*v.c;if(d<0)return{value:'No real roots',detail:'The discriminant is negative.'};if(d===0)return{value:String(-v.b/(2*v.a)),detail:'One repeated real root.'};return{value:`${(-v.b+Math.sqrt(d))/(2*v.a)}, ${(-v.b-Math.sqrt(d))/(2*v.a)}`,detail:'Two real roots.'}}}
,{id:'permutations',title:'Permutation Calculator',category:'Math',icon:'n!',description:'Calculate ordered arrangements of n items taken r at a time.',fields:[['n','Total items (n)','number'],['r','Selected items (r)','number']],run:v=>{if(!Number.isInteger(v.n)||!Number.isInteger(v.r)||v.n<0||v.r<0||v.r>v.n)throw Error('Use integers with 0 ≤ r ≤ n.');let out=1;for(let i=0;i<v.r;i++)out*=v.n-i;return{value:out,detail:'Order matters.'}}}
,{id:'combinations',title:'Combination Calculator',category:'Math',icon:'C',description:'Calculate unordered selections of n items taken r at a time.',fields:[['n','Total items (n)','number'],['r','Selected items (r)','number']],run:v=>{if(!Number.isInteger(v.n)||!Number.isInteger(v.r)||v.n<0||v.r<0||v.r>v.n)throw Error('Use integers with 0 ≤ r ≤ n.');let r=Math.min(v.r,v.n-v.r),out=1;for(let i=1;i<=r;i++)out=out*(v.n-r+i)/i;return{value:Math.round(out),detail:'Order does not matter.'}}}
,{id:'sphere-volume',title:'Sphere Volume',category:'Geometry',icon:'◉',description:'Calculate the volume of a sphere from its radius.',fields:[['radius','Radius','number']],run:v=>{if(v.radius<0)throw Error('Radius cannot be negative.');return{value:4/3*Math.PI*v.radius**3,unit:' cubic units'}}}
,{id:'cylinder-volume',title:'Cylinder Volume',category:'Geometry',icon:'▥',description:'Calculate cylinder volume from radius and height.',fields:[['radius','Radius','number'],['height','Height','number']],run:v=>{if(v.radius<0||v.height<0)throw Error('Dimensions cannot be negative.');return{value:Math.PI*v.radius*v.radius*v.height,unit:' cubic units'}}}
,{id:'pounds-kilograms',title:'Pounds to Kilograms',category:'Conversion',icon:'⚖',description:'Convert pounds into kilograms.',fields:[['pounds','Pounds','number']],run:v=>({value:v.pounds*0.45359237,unit:' kg'})}
,{id:'liters-gallons',title:'Liters to US Gallons',category:'Conversion',icon:'🧪',description:'Convert liters into US liquid gallons.',fields:[['liters','Liters','number']],run:v=>({value:v.liters*0.2641720524,unit:' US gal'})}
,{id:'split-bill',title:'Bill Split Calculator',category:'Everyday',icon:'🍽',description:'Split a bill evenly, including an optional tip.',fields:[['bill','Bill amount','number'],['tip','Tip (%)','number'],['people','Number of people','number']],run:v=>{if(v.people<=0)throw Error('People must be positive.');const total=v.bill*(1+v.tip/100);return{value:total/v.people,detail:`Total bill: ${total.toFixed(2)}; split across ${v.people} people.`}}}

,{id:'date-add',title:'Add Days to Date',category:'Time & Date',icon:'➕',description:'Add a whole number of days to a date.',fields:[['date','Start date','date'],['days','Days to add','number']],run:v=>{const d=new Date(v.date+'T00:00:00');if(Number.isNaN(d.getTime()))throw Error('Enter a valid date.');d.setDate(d.getDate()+v.days);return{value:d.toISOString().slice(0,10),detail:'The result uses the device date handling.'}}}
,{id:'date-subtract',title:'Subtract Dates',category:'Time & Date',icon:'➖',description:'Find the date a number of days before a selected date.',fields:[['date','End date','date'],['days','Days to subtract','number']],run:v=>{const d=new Date(v.date+'T00:00:00');if(Number.isNaN(d.getTime()))throw Error('Enter a valid date.');d.setDate(d.getDate()-v.days);return{value:d.toISOString().slice(0,10)}}}
,{id:'future-value',title:'Future Value Calculator',category:'Finance',icon:'📈',description:'Estimate future value with regular compounding.',fields:[['principal','Starting amount','number'],['rate','Annual rate (%)','number'],['years','Years','number'],['frequency','Compounds per year','number']],run:v=>{if(v.frequency<=0||v.years<0)throw Error('Use a positive frequency and non-negative years.');return{value:v.principal*Math.pow(1+v.rate/100/v.frequency,v.frequency*v.years),detail:'Estimated future balance before taxes and fees.'}}}
,{id:'net-worth',title:'Net Worth Calculator',category:'Finance',icon:'💰',description:'Estimate net worth by subtracting liabilities from assets.',fields:[['assets','Total assets','number'],['liabilities','Total liabilities','number']],run:v=>({value:v.assets-v.liabilities,detail:'Net worth equals assets minus liabilities.'})}
,{id:'parallelogram-area',title:'Parallelogram Area',category:'Geometry',icon:'▱',description:'Calculate parallelogram area from base and perpendicular height.',fields:[['base','Base','number'],['height','Height','number']],run:v=>{if(v.base<0||v.height<0)throw Error('Dimensions cannot be negative.');return{value:v.base*v.height,unit:' square units'}}}
,{id:'trapezoid-area',title:'Trapezoid Area',category:'Geometry',icon:'⏢',description:'Calculate trapezoid area from two parallel sides and height.',fields:[['a','Parallel side A','number'],['b','Parallel side B','number'],['height','Height','number']],run:v=>{if(v.a<0||v.b<0||v.height<0)throw Error('Dimensions cannot be negative.');return{value:(v.a+v.b)*v.height/2,unit:' square units'}}}
,{id:'ounces-grams',title:'Ounces to Grams',category:'Conversion',icon:'⚖',description:'Convert avoirdupois ounces into grams.',fields:[['ounces','Ounces','number']],run:v=>({value:v.ounces*28.349523125,unit:' g'})}
,{id:'yards-meters',title:'Yards to Meters',category:'Conversion',icon:'📏',description:'Convert yards into meters.',fields:[['yards','Yards','number']],run:v=>({value:v.yards*0.9144,unit:' m'})}
,{id:'percent-of-total',title:'Percent of Total',category:'Math',icon:'％',description:'Find what percentage one value is of a total.',fields:[['part','Part','number'],['total','Total','number']],run:v=>{if(v.total===0)throw Error('Total must not be zero.');return{value:v.part/v.total*100,unit:' %'}}}
,{id:'weighted-average',title:'Weighted Average',category:'Math',icon:'∑',description:'Calculate a weighted average for two values.',fields:[['value1','Value 1','number'],['weight1','Weight 1 (%)','number'],['value2','Value 2','number'],['weight2','Weight 2 (%)','number']],run:v=>{const total=v.weight1+v.weight2;if(total===0)throw Error('Weights must not total zero.');return{value:(v.value1*v.weight1+v.value2*v.weight2)/total,detail:'Weights are normalized by their combined total.'}}}

,{id:'vat-calculator',title:'VAT Calculator',category:'Finance',icon:'🧾',description:'Calculate VAT amount and total price from a net amount.',fields:[['net','Net amount','number'],['rate','VAT rate (%)','number']],run:v=>{if(v.net<0||v.rate<0)throw Error('Amounts and rate cannot be negative.');const vat=v.net*v.rate/100;return{value:v.net+vat,detail:`VAT amount: ${vat.toFixed(2)}; net amount: ${v.net.toFixed(2)}.`}}}
,{id:'profit-margin',title:'Profit Margin Calculator',category:'Finance',icon:'📊',description:'Calculate profit and profit margin from revenue and cost.',fields:[['revenue','Revenue','number'],['cost','Cost','number']],run:v=>{if(v.revenue<=0||v.cost<0)throw Error('Revenue must be positive and cost cannot be negative.');const profit=v.revenue-v.cost;return{value:profit/v.revenue*100,unit:' %',detail:`Profit: ${profit.toFixed(2)}.`}}}
,{id:'break-even',title:'Break-Even Point Calculator',category:'Finance',icon:'⚖',description:'Find the units needed to cover fixed costs.',fields:[['fixed','Fixed costs','number'],['price','Price per unit','number'],['variable','Variable cost per unit','number']],run:v=>{const margin=v.price-v.variable;if(v.fixed<0||margin<=0)throw Error('Fixed costs must be non-negative and price must exceed variable cost.');return{value:v.fixed/margin,unit:' units'}}}
,{id:'average-speed',title:'Average Speed Calculator',category:'Science',icon:'🚗',description:'Calculate average speed from total distance and total time.',fields:[['distance','Total distance','number'],['time','Total time','number']],run:v=>{if(v.distance<0||v.time<=0)throw Error('Distance cannot be negative and time must be positive.');return{value:v.distance/v.time,unit:' distance units/time unit'}}}
,{id:'force-calculator',title:'Force Calculator',category:'Science',icon:'🧲',description:'Calculate force using mass multiplied by acceleration.',fields:[['mass','Mass (kg)','number'],['acceleration','Acceleration (m/s²)','number']],run:v=>{if(v.mass<0)throw Error('Mass cannot be negative.');return{value:v.mass*v.acceleration,unit:' N'}}}
,{id:'kinetic-energy',title:'Kinetic Energy Calculator',category:'Science',icon:'⚡',description:'Calculate kinetic energy from mass and velocity.',fields:[['mass','Mass (kg)','number'],['velocity','Velocity (m/s)','number']],run:v=>{if(v.mass<0)throw Error('Mass cannot be negative.');return{value:0.5*v.mass*v.velocity*v.velocity,unit:' J'}}}
,{id:'cubic-volume',title:'Cube Volume Calculator',category:'Geometry',icon:'🧊',description:'Calculate the volume of a cube from its side length.',fields:[['side','Side length','number']],run:v=>{if(v.side<0)throw Error('Side length cannot be negative.');return{value:v.side**3,unit:' cubic units'}}}
,{id:'hexagon-area',title:'Regular Hexagon Area',category:'Geometry',icon:'⬡',description:'Calculate the area of a regular hexagon from its side length.',fields:[['side','Side length','number']],run:v=>{if(v.side<0)throw Error('Side length cannot be negative.');return{value:3*Math.sqrt(3)*v.side*v.side/2,unit:' square units'}}}
,{id:'millimeters-inches',title:'Millimeters to Inches',category:'Conversion',icon:'📏',description:'Convert millimeters into inches.',fields:[['millimeters','Millimeters','number']],run:v=>({value:v.millimeters/25.4,unit:' in'})}
,{id:'celsius-kelvin',title:'Celsius to Kelvin',category:'Conversion',icon:'🌡',description:'Convert Celsius temperature into Kelvin.',fields:[['celsius','Celsius','number']],run:v=>{if(v.celsius<-273.15)throw Error('Temperature cannot be below absolute zero.');return{value:v.celsius+273.15,unit:' K'}}}


,{id:'discount-price',title:'Discount Price Calculator',category:'Finance',icon:'🏷️',description:'Calculate the final price after applying a discount.',fields:[['price','Original price','number'],['discount','Discount (%)','number']],run:v=>{if(v.price<0||v.discount<0||v.discount>100)throw Error('Enter a valid price and discount from 0 to 100.');return{value:v.price*(1-v.discount/100),detail:`You save ${v.price*v.discount/100}.`}}},
{id:'pace',title:'Running Pace Calculator',category:'Health',icon:'🏃',description:'Calculate average running pace from distance and time.',fields:[['distance','Distance (km)','number'],['minutes','Time (minutes)','number']],run:v=>{if(v.distance<=0||v.minutes<=0)throw Error('Distance and time must be positive.');return{value:v.minutes/v.distance,unit:'min/km'}}},
{id:'rectangle-perimeter',title:'Rectangle Perimeter',category:'Geometry',icon:'▭',description:'Find the perimeter of a rectangle.',fields:[['length','Length','number'],['width','Width','number']],run:v=>{if(v.length<=0||v.width<=0)throw Error('Length and width must be positive.');return{value:2*(v.length+v.width),unit:'units'}}},
{id:'kilograms-pounds',title:'Kilograms to Pounds',category:'Conversion',icon:'⚖️',description:'Convert kilograms into pounds.',fields:[['kilograms','Kilograms','number']],run:v=>{if(v.kilograms<0)throw Error('Kilograms must not be negative.');return{value:v.kilograms*2.2046226218,unit:'lb'}}},
,{id:'body-surface-area',title:'Body Surface Area Calculator',category:'Health',icon:'🧍',description:'Estimate body surface area using height and weight.',fields:[['weight','Weight (kg)','number'],['height','Height (cm)','number']],run:v=>{if(v.weight<=0||v.height<=0)throw Error('Weight and height must be positive.');return{value:Math.sqrt(v.weight*v.height/3600),unit:' m²',detail:'Estimate using the Mosteller formula.'}}}
,{id:'ideal-weight',title:'Ideal Weight Calculator',category:'Health',icon:'⚖️',description:'Estimate a reference weight range from height.',fields:[['height','Height (cm)','number']],run:v=>{if(v.height<=0)throw Error('Height must be positive.');const m=v.height/100;return{value:18.5*m*m,unit:'–'+(24.9*m*m)+' kg',detail:'Reference range based on BMI 18.5 to 24.9.'}}}
,{id:'triangle-perimeter',title:'Triangle Perimeter Calculator',category:'Geometry',icon:'🔺',description:'Find the perimeter of a triangle from its three sides.',fields:[['a','Side A','number'],['b','Side B','number'],['c','Side C','number']],run:v=>{if(v.a<=0||v.b<=0||v.c<=0||v.a+v.b<=v.c||v.a+v.c<=v.b||v.b+v.c<=v.a)throw Error('Enter valid triangle sides.');return{value:v.a+v.b+v.c,unit:' units'}}}
,{id:'cylinder-volume',title:'Cylinder Volume Calculator',category:'Geometry',icon:'🥫',description:'Calculate the volume of a cylinder.',fields:[['radius','Radius','number'],['height','Height','number']],run:v=>{if(v.radius<=0||v.height<=0)throw Error('Radius and height must be positive.');return{value:Math.PI*v.radius*v.radius*v.height,unit:' cubic units'}}}
,{id:'ohms-law-current',title:'Ohm’s Law Current Calculator',category:'Science',icon:'⚡',description:'Calculate electric current from voltage and resistance.',fields:[['voltage','Voltage (V)','number'],['resistance','Resistance (Ω)','number']],run:v=>{if(v.voltage<0||v.resistance<=0)throw Error('Voltage must not be negative and resistance must be positive.');return{value:v.voltage/v.resistance,unit:' A'}}}
,{id:'pressure',title:'Pressure Calculator',category:'Science',icon:'🧪',description:'Calculate pressure from force and area.',fields:[['force','Force (N)','number'],['area','Area (m²)','number']],run:v=>{if(v.force<0||v.area<=0)throw Error('Force must not be negative and area must be positive.');return{value:v.force/v.area,unit:' Pa'}}}
,{id:'liters-milliliters',title:'Liters to Milliliters Converter',category:'Conversion',icon:'🧴',description:'Convert liters into milliliters.',fields:[['liters','Liters','number']],run:v=>{if(v.liters<0)throw Error('Liters must not be negative.');return{value:v.liters*1000,unit:' mL'}}}

,{id:'sales-commission',title:'Sales Commission Calculator',category:'Finance',icon:'💼',description:'Calculate commission earned from sales.',fields:[['sales','Sales amount','number'],['rate','Commission rate (%)','number']],run:v=>{if(v.sales<0||v.rate<0)throw Error('Sales and rate must not be negative.');return{value:v.sales*v.rate/100,unit:'',detail:'Estimated commission earned.'}}}
,{id:'loan-to-value',title:'Loan to Value Calculator',category:'Finance',icon:'🏠',description:'Calculate loan-to-value ratio from loan and property value.',fields:[['loan','Loan amount','number'],['property','Property value','number']],run:v=>{if(v.loan<0||v.property<=0)throw Error('Loan cannot be negative and property value must be positive.');return{value:v.loan/v.property*100,unit:' %'}}}
,{id:'calorie-burn',title:'Calorie Burn Estimate',category:'Health',icon:'🔥',description:'Estimate calories burned during an activity.',fields:[['met','MET value','number'],['weight','Weight (kg)','number'],['minutes','Duration (minutes)','number']],run:v=>{if(v.met<=0||v.weight<=0||v.minutes<=0)throw Error('All values must be positive.');return{value:v.met*3.5*v.weight/200*v.minutes,unit:' kcal',detail:'General estimate; actual energy use varies.'}}}
,{id:'waist-height-ratio',title:'Waist to Height Ratio',category:'Health',icon:'📏',description:'Calculate waist-to-height ratio as a screening measure.',fields:[['waist','Waist circumference (cm)','number'],['height','Height (cm)','number']],run:v=>{if(v.waist<=0||v.height<=0)throw Error('Measurements must be positive.');return{value:v.waist/v.height,detail:'Screening estimate, not a diagnosis.'}}}
,{id:'sphere-surface-area',title:'Sphere Surface Area Calculator',category:'Geometry',icon:'⚪',description:'Calculate the surface area of a sphere.',fields:[['radius','Radius','number']],run:v=>{if(v.radius<0)throw Error('Radius must not be negative.');return{value:4*Math.PI*v.radius*v.radius,unit:' square units'}}}
,{id:'cone-volume',title:'Cone Volume Calculator',category:'Geometry',icon:'🔻',description:'Calculate the volume of a cone.',fields:[['radius','Radius','number'],['height','Height','number']],run:v=>{if(v.radius<=0||v.height<=0)throw Error('Radius and height must be positive.');return{value:Math.PI*v.radius*v.radius*v.height/3,unit:' cubic units'}}}
,{id:'work-energy',title:'Work Calculator',category:'Science',icon:'🛠️',description:'Calculate mechanical work from force and distance.',fields:[['force','Force (N)','number'],['distance','Distance (m)','number']],run:v=>{if(v.force<0||v.distance<0)throw Error('Force and distance must not be negative.');return{value:v.force*v.distance,unit:' J'}}}
,{id:'watts-calculator',title:'Power in Watts Calculator',category:'Science',icon:'🔌',description:'Calculate electrical power from voltage and current.',fields:[['voltage','Voltage (V)','number'],['current','Current (A)','number']],run:v=>{if(v.voltage<0||v.current<0)throw Error('Voltage and current must not be negative.');return{value:v.voltage*v.current,unit:' W'}}}
,{id:'grams-ounces',title:'Grams to Ounces Converter',category:'Conversion',icon:'⚖️',description:'Convert grams into ounces.',fields:[['grams','Grams','number']],run:v=>{if(v.grams<0)throw Error('Grams must not be negative.');return{value:v.grams/28.349523125,unit:' oz'}}}
,{id:'minutes-hours',title:'Minutes to Hours Converter',category:'Conversion',icon:'⏱️',description:'Convert minutes into hours.',fields:[['minutes','Minutes','number']],run:v=>{if(v.minutes<0)throw Error('Minutes must not be negative.');return{value:v.minutes/60,unit:' hours'}}}

,
{id:'tip-calculator',title:'Tip Calculator',category:'Finance',icon:'💵',description:'Calculate a tip and split the bill.',fields:[['bill','Bill amount','number'],['rate','Tip rate (%)','number'],['people','People','number']],run:v=>{if(v.bill<0||v.rate<0||v.people<=0)throw Error('Enter valid values.');return{value:v.bill*v.rate/100/v.people,unit:' per person'}}},
{id:'savings-goal',title:'Savings Goal Calculator',category:'Finance',icon:'🎯',description:'Estimate monthly savings needed for a target.',fields:[['target','Target amount','number'],['saved','Already saved','number'],['months','Months','number']],run:v=>{if(v.months<=0)throw Error('Months must be positive.');return{value:(v.target-v.saved)/v.months,unit:' per month'}}},
{id:'inflation-adjustment',title:'Inflation Adjustment Calculator',category:'Finance',icon:'💰',description:'Estimate future value after inflation.',fields:[['amount','Current amount','number'],['rate','Inflation rate (%)','number'],['years','Years','number']],run:v=>({value:v.amount*Math.pow(1+v.rate/100,v.years),detail:'Estimated future price equivalent.'})},
{id:'lean-body-mass',title:'Lean Body Mass Calculator',category:'Health',icon:'⚖️',description:'Estimate lean body mass using the Boer formula.',fields:[['weight','Weight (kg)','number'],['height','Height (cm)','number'],['sex','Sex: male or female','text']],run:v=>{const s=v.sex.toLowerCase();if(v.weight<=0||v.height<=0||!['male','female'].includes(s))throw Error('Enter valid values.');return{value:s==='male'?0.407*v.weight+0.267*v.height-19.2:0.252*v.weight+0.473*v.height-48.3,unit:' kg'}}},
{id:'body-fat-navy',title:'Navy Body Fat Estimate',category:'Health',icon:'📏',description:'Estimate body fat using body measurements.',fields:[['waist','Waist (cm)','number'],['neck','Neck (cm)','number'],['height','Height (cm)','number'],['sex','Sex: male or female','text']],run:v=>{const s=v.sex.toLowerCase();if(v.waist<=v.neck||v.neck<=0||v.height<=0||!['male','female'].includes(s))throw Error('Enter valid values.');const x=s==='male'?495/(1.0324-0.19077*Math.log10(v.waist-v.neck)+0.15456*Math.log10(v.height))-450:495/(1.29579-0.35004*Math.log10(v.waist+0)-0.22100*Math.log10(v.height))-450;return{value:x,unit:' %',detail:'Approximate screening estimate.'}}},
{id:'triangle-perimeter-sss',title:'Triangle Perimeter SSS',category:'Geometry',icon:'🔺',description:'Calculate perimeter from three sides.',fields:[['a','Side A','number'],['b','Side B','number'],['c','Side C','number']],run:v=>{if(v.a+v.b<=v.c||v.a+v.c<=v.b||v.b+v.c<=v.a)throw Error('Sides must form a triangle.');return{value:v.a+v.b+v.c,unit:' units'}}},
{id:'pyramid-volume',title:'Pyramid Volume Calculator',category:'Geometry',icon:'🔻',description:'Calculate a pyramid volume.',fields:[['baseArea','Base area','number'],['height','Height','number']],run:v=>({value:v.baseArea*v.height/3,unit:' cubic units'})},
{id:'density',title:'Density Calculator',category:'Science',icon:'🧪',description:'Calculate density from mass and volume.',fields:[['mass','Mass','number'],['volume','Volume','number']],run:v=>{if(v.volume<=0)throw Error('Volume must be positive.');return{value:v.mass/v.volume,unit:' mass/volume'}}},
{id:'force',title:'Force Calculator',category:'Science',icon:'💥',description:'Calculate force using mass and acceleration.',fields:[['mass','Mass (kg)','number'],['acceleration','Acceleration (m/s²)','number']],run:v=>({value:v.mass*v.acceleration,unit:' N'})},
{id:'potential-energy',title:'Potential Energy Calculator',category:'Science',icon:'🏔️',description:'Calculate gravitational potential energy.',fields:[['mass','Mass (kg)','number'],['height','Height (m)','number'],['gravity','Gravity (m/s²)','number']],run:v=>({value:v.mass*v.height*v.gravity,unit:' J'})},
{id:'meters-yards',title:'Meters to Yards',category:'Conversion',icon:'📏',description:'Convert meters to yards.',fields:[['meters','Meters','number']],run:v=>({value:v.meters*1.0936132983,unit:' yd'})}
,
{id:'monthly-savings-growth',title:'Monthly Savings Growth',category:'Finance',icon:'💹',description:'Estimate savings growth with regular deposits.',fields:[['deposit','Monthly deposit','number'],['rate','Annual rate (%)','number'],['months','Months','number']],run:v=>{if(v.months<=0)throw Error('Months must be positive.');const r=v.rate/1200;return{value:r===0?v.deposit*v.months:v.deposit*(Math.pow(1+r,v.months)-1)/r,unit:''}}},
{id:'currency-markup',title:'Currency Markup Calculator',category:'Finance',icon:'💱',description:'Calculate a price after a markup percentage.',fields:[['amount','Amount','number'],['markup','Markup (%)','number']],run:v=>({value:v.amount*(1+v.markup/100)})},
{id:'ideal-calorie-intake',title:'Daily Calorie Intake Estimate',category:'Health',icon:'🍎',description:'Estimate daily calories using BMR and activity level.',fields:[['bmr','BMR','number'],['activity','Activity multiplier','number']],run:v=>{if(v.bmr<=0||v.activity<=0)throw Error('Values must be positive.');return{value:v.bmr*v.activity,unit:' kcal/day',detail:'General estimate; individual needs vary.'}}},
{id:'rectangle-diagonal',title:'Rectangle Diagonal Calculator',category:'Geometry',icon:'📐',description:'Calculate a rectangle diagonal.',fields:[['length','Length','number'],['width','Width','number']],run:v=>({value:Math.hypot(v.length,v.width),unit:' units'})},
{id:'regular-polygon-interior',title:'Polygon Interior Angle',category:'Geometry',icon:'🔷',description:'Calculate each interior angle of a regular polygon.',fields:[['sides','Number of sides','number']],run:v=>{if(v.sides<3)throw Error('Use at least 3 sides.');return{value:(v.sides-2)*180/v.sides,unit:' degrees'}}},
{id:'momentum',title:'Momentum Calculator',category:'Science',icon:'🚀',description:'Calculate momentum from mass and velocity.',fields:[['mass','Mass (kg)','number'],['velocity','Velocity (m/s)','number']],run:v=>({value:v.mass*v.velocity,unit:' kg·m/s'})},
{id:'frequency-period',title:'Frequency to Period Calculator',category:'Science',icon:'〰️',description:'Calculate period from frequency.',fields:[['frequency','Frequency (Hz)','number']],run:v=>{if(v.frequency<=0)throw Error('Frequency must be positive.');return{value:1/v.frequency,unit:' s'}}},
{id:'feet-inches',title:'Feet to Inches Converter',category:'Conversion',icon:'📏',description:'Convert feet into inches.',fields:[['feet','Feet','number']],run:v=>({value:v.feet*12,unit:' inches'})},
,
{id:'ounces-pounds',title:'Ounces to Pounds Converter',category:'Conversion',icon:'⚖️',description:'Convert ounces into pounds.',fields:[['ounces','Ounces','number']],run:v=>({value:v.ounces/16,unit:' lb'})}

,{id:'sales-margin',title:'Sales Margin Calculator',category:'Finance',icon:'💹',description:'Calculate profit margin from revenue and cost.',fields:[['revenue','Revenue','number'],['cost','Cost','number']],run:v=>{if(v.revenue<=0)throw Error('Revenue must be positive.');return{value:(v.revenue-v.cost)/v.revenue*100,unit:' %',detail:'Profit margin as a percentage of revenue.'}}},
{id:'break-even-units',title:'Break-Even Units Calculator',category:'Finance',icon:'⚖️',description:'Estimate units needed to cover fixed costs.',fields:[['fixed','Fixed costs','number'],['price','Price per unit','number'],['variable','Variable cost per unit','number']],run:v=>{const d=v.price-v.variable;if(d<=0)throw Error('Price must exceed variable cost.');return{value:v.fixed/d,unit:' units'}}},
{id:'future-value',title:'Future Value Calculator',category:'Finance',icon:'📈',description:'Estimate future value with periodic growth.',fields:[['principal','Principal','number'],['rate','Annual rate (%)','number'],['years','Years','number']],run:v=>({value:v.principal*Math.pow(1+v.rate/100,v.years)})},
{id:'present-value',title:'Present Value Calculator',category:'Finance',icon:'💰',description:'Discount a future amount to present value.',fields:[['future','Future value','number'],['rate','Annual discount rate (%)','number'],['years','Years','number']],run:v=>{if(1+v.rate/100<=0)throw Error('Rate is invalid.');return{value:v.future/Math.pow(1+v.rate/100,v.years)}}},
{id:'investment-return',title:'Investment Return Calculator',category:'Finance',icon:'📊',description:'Calculate return percentage on an investment.',fields:[['initial','Initial investment','number'],['finalValue','Final value','number']],run:v=>{if(v.initial===0)throw Error('Initial investment cannot be zero.');return{value:(v.finalValue-v.initial)/Math.abs(v.initial)*100,unit:' %'}}},
{id:'hourly-pay',title:'Hourly Pay Calculator',category:'Finance',icon:'💵',description:'Convert hourly pay and hours into gross earnings.',fields:[['rate','Hourly rate','number'],['hours','Hours worked','number']],run:v=>({value:v.rate*v.hours,unit:' currency units'})},
{id:'overtime-pay',title:'Overtime Pay Calculator',category:'Finance',icon:'⏰',description:'Estimate overtime earnings using a multiplier.',fields:[['rate','Regular hourly rate','number'],['hours','Overtime hours','number'],['multiplier','Overtime multiplier','number']],run:v=>({value:v.rate*v.hours*v.multiplier,unit:' currency units'})},
{id:'rent-affordability',title:'Rent Affordability Calculator',category:'Finance',icon:'🏠',description:'Estimate a rent budget from monthly income.',fields:[['income','Monthly income','number'],['percent','Budget percentage (%)','number']],run:v=>({value:v.income*v.percent/100,unit:' currency units/month'})},
{id:'calorie-percentage',title:'Calorie Percentage Calculator',category:'Health',icon:'🍽️',description:'Find the percentage of calories from a food amount.',fields:[['food','Food calories','number'],['total','Total calories','number']],run:v=>{if(v.total<=0)throw Error('Total calories must be positive.');return{value:v.food/v.total*100,unit:' %'}}},
{id:'macro-split',title:'Macro Split Calculator',category:'Health',icon:'🥗',description:'Estimate calories from grams of protein, carbs, and fat.',fields:[['protein','Protein grams','number'],['carbs','Carbohydrate grams','number'],['fat','Fat grams','number']],run:v=>({value:v.protein*4+v.carbs*4+v.fat*9,unit:' kcal',detail:'Uses 4 kcal/g for protein and carbs and 9 kcal/g for fat.'})},
{id:'target-heart-rate',title:'Target Heart Rate Calculator',category:'Health',icon:'❤️',description:'Estimate a target heart rate from age and intensity.',fields:[['age','Age','number'],['intensity','Intensity (%)','number']],run:v=>{if(v.age<=0)throw Error('Age must be positive.');return{value:(220-v.age)*v.intensity/100,unit:' bpm',detail:'Simple estimated maximum-heart-rate method.'}}},
{id:'water-intake',title:'Water Intake Estimate',category:'Health',icon:'💧',description:'Estimate daily water intake from body weight.',fields:[['weight','Weight (kg)','number'],['factor','Milliliters per kg','number']],run:v=>({value:v.weight*v.factor,unit:' mL/day',detail:'General estimate; individual needs vary.'})},
{id:'trapezoid-area',title:'Trapezoid Area Calculator',category:'Geometry',icon:'⏢',description:'Calculate trapezoid area from two parallel sides and height.',fields:[['a','Base A','number'],['b','Base B','number'],['height','Height','number']],run:v=>({value:(v.a+v.b)*v.height/2,unit:' square units'})},
{id:'parallelogram-area',title:'Parallelogram Area Calculator',category:'Geometry',icon:'▱',description:'Calculate area from base and perpendicular height.',fields:[['base','Base','number'],['height','Height','number']],run:v=>({value:v.base*v.height,unit:' square units'})},
{id:'ellipse-area',title:'Ellipse Area Calculator',category:'Geometry',icon:'⭕',description:'Calculate ellipse area from its semi-axes.',fields:[['a','Semi-major axis','number'],['b','Semi-minor axis','number']],run:v=>({value:Math.PI*v.a*v.b,unit:' square units'})},
{id:'prism-volume',title:'Prism Volume Calculator',category:'Geometry',icon:'🔷',description:'Calculate prism volume from base area and height.',fields:[['baseArea','Base area','number'],['height','Height','number']],run:v=>({value:v.baseArea*v.height,unit:' cubic units'})},
{id:'kinetic-energy',title:'Kinetic Energy Calculator',category:'Science',icon:'⚡',description:'Calculate kinetic energy from mass and velocity.',fields:[['mass','Mass (kg)','number'],['velocity','Velocity (m/s)','number']],run:v=>({value:.5*v.mass*v.velocity*v.velocity,unit:' J'})},
{id:'voltage-divider',title:'Voltage Divider Calculator',category:'Science',icon:'🔌',description:'Calculate output voltage in a two-resistor divider.',fields:[['input','Input voltage','number'],['r1','R1','number'],['r2','R2','number']],run:v=>{if(v.r1+v.r2===0)throw Error('Resistance sum cannot be zero.');return{value:v.input*v.r2/(v.r1+v.r2),unit:' V'}}},
{id:'kilograms-grams',title:'Kilograms to Grams Converter',category:'Conversion',icon:'⚖️',description:'Convert kilograms into grams.',fields:[['kg','Kilograms','number']],run:v=>({value:v.kg*1000,unit:' g'})},
{id:'celsius-kelvin',title:'Celsius to Kelvin Converter',category:'Conversion',icon:'🌡️',description:'Convert Celsius temperature into Kelvin.',fields:[['celsius','Temperature (°C)','number']],run:v=>({value:v.celsius+273.15,unit:' K'})},

,{id:'compound-growth-monthly',title:'Monthly Compound Growth',category:'Finance',icon:'📈',description:'Estimate growth with monthly compounding.',fields:[['principal','Principal','number'],['rate','Annual rate (%)','number'],['months','Months','number']],run:v=>({value:v.principal*Math.pow(1+v.rate/1200,v.months)})}
,{id:'unit-price',title:'Unit Price Calculator',category:'Finance',icon:'🏷️',description:'Find the price per unit from total cost and quantity.',fields:[['total','Total cost','number'],['quantity','Quantity','number']],run:v=>{if(v.quantity<=0)throw Error('Quantity must be positive.');return{value:v.total/v.quantity,unit:' per unit'}}}
,{id:'rhombus-area',title:'Rhombus Area Calculator',category:'Geometry',icon:'🔶',description:'Calculate rhombus area from diagonals.',fields:[['d1','Diagonal 1','number'],['d2','Diagonal 2','number']],run:v=>({value:v.d1*v.d2/2,unit:' square units'})}
,{id:'angular-velocity',title:'Angular Velocity Calculator',category:'Science',icon:'🔄',description:'Calculate angular velocity from angle and time.',fields:[['angle','Angle (radians)','number'],['time','Time (seconds)','number']],run:v=>{if(v.time===0)throw Error('Time cannot be zero.');return{value:v.angle/v.time,unit:' rad/s'}}}
,{id:'millimeters-centimeters',title:'Millimeters to Centimeters',category:'Conversion',icon:'📏',description:'Convert millimeters into centimeters.',fields:[['mm','Millimeters','number']],run:v=>({value:v.mm/10,unit:' cm'})}

,{id:'fahrenheit-kelvin',title:'Fahrenheit to Kelvin Converter',category:'Conversion',icon:'🌡️',description:'Convert Fahrenheit temperature into Kelvin.',fields:[['fahrenheit','Temperature (°F)','number']],run:v=>({value:(v.fahrenheit-32)*5/9+273.15,unit:' K'})}
].filter(Boolean).filter((c,i,a)=>a.findIndex(x=>x.id===c.id)===i);

const contentByCategory={
  Math:{formula:'Apply the stated arithmetic formula to the entered values.',example:'Enter small whole numbers first, then compare the result with a manual calculation.',tips:'Keep signs, decimal places, and units consistent.'},
  Finance:{formula:'The displayed formula is an estimate and may exclude fees, taxes, compounding assumptions, or lender-specific rules.',example:'Test the calculator with a small principal and a short period before using larger values.',tips:'Confirm the rate, time period, payment frequency, and any excluded charges.'},
  Health:{formula:'This tool uses a screening or estimation formula and is not a medical diagnosis.',example:'Use measured inputs and review the units before interpreting the result.',tips:'Results can vary with age, sex, activity, health status, and measurement method. Consult a qualified professional for medical decisions.'},
  'Time & Date':{formula:'Dates are interpreted using the device date handling and the selected calendar values.',example:'Try two dates whose difference you already know.',tips:'Time zones, daylight-saving changes, and inclusive/exclusive counting can affect date results.'},
  Science:{formula:'Use consistent measurement units and the physical relationship shown for this tool.',example:'Start with simple values and verify the unit of the output.',tips:'Do not mix incompatible units without converting them first.'},
  Geometry:{formula:'The geometric formula uses the dimensions entered in consistent units.',example:'Use a simple shape with known dimensions to check the result.',tips:'The output unit is squared for area and cubed for volume.'},
  Conversion:{formula:'The conversion applies a fixed relationship between the selected units.',example:'Convert a familiar value such as 1 or 10 units first.',tips:'Check the direction of conversion and the output unit.'}
};
const fallbackContent={formula:'Apply the formula shown for this calculator.',example:'Start with simple known values to check your inputs.',tips:'Review units, assumptions, and rounding before relying on the result.'};
for(const c of calculators){const t=contentByCategory[c.category]||fallbackContent;c.formula=c.formula||t.formula;c.example=c.example||t.example;c.tips=c.tips||t.tips;c.faqs=c.faqs||[`What does this calculator do? It calculates ${c.title.toLowerCase()} from the values you enter.`,`Can I use decimal values? Yes, where the input field accepts numbers.`,`Should I rely on the result for important decisions? Review assumptions, units, and professional guidance where relevant.`];c.seoTitle=`${c.title} | Free CalcPro Calculator`;c.seoDescription=`Use CalcPro's ${c.title.toLowerCase()} with clear inputs, a formula explanation, examples, and practical tips.`;}

if(typeof document!=='undefined'){
const $=s=>document.querySelector(s);
const state={query:'',category:'all'};
const categoryMeta={
  Math:{icon:'▦',description:'Algebra, geometry, statistics and more.'},
  Finance:{icon:'▤',description:'Loans, mortgage, investment, tax and more.'},
  Health:{icon:'♡',description:'BMI, BMR, body fat, pregnancy and more.'},
  'Time & Date':{icon:'◷',description:'Age, date difference, time zones and more.'},
  Conversion:{icon:'⇄',description:'Length, weight, temperature and more.'},
  Geometry:{icon:'⌂',description:'Shapes, areas, volume and dimensions.'},
  Science:{icon:'ϟ',description:'Physics formulas and useful science tools.'},
  Business:{icon:'▥',description:'Profit, margin, tax and business planning.'},
  Lifestyle:{icon:'⌂',description:'Daily life and personal-use calculators.'}
};
function fmt(x){return typeof x==='number'?Number(x.toFixed(8)).toLocaleString():x}
function filtered(){return calculators.filter(c=>(state.category==='all'||c.category===state.category)&&`${c.title} ${c.description}`.toLowerCase().includes(state.query.toLowerCase()))}
function renderCategoryCards(){
  const counts={};calculators.forEach(c=>counts[c.category]=(counts[c.category]||0)+1);
  const order=['Finance','Health','Math','Time & Date','Conversion','Geometry','Science','Business','Lifestyle'];
  const cats=[...new Set([...order,...Object.keys(counts)])].filter(c=>counts[c]);
  $('#category-cards').innerHTML=cats.slice(0,9).map(cat=>{const m=categoryMeta[cat]||{icon:'◈',description:'Useful everyday calculation tools.'};return `<a href="#tools" class="category-card" data-category="${cat}"><span class="category-icon">${m.icon}</span><div><h3>${cat} Calculators</h3><p>${m.description}</p><small>${counts[cat]}+ calculators →</small></div></a>`}).join('');
  document.querySelectorAll('[data-category]').forEach(el=>el.addEventListener('click',()=>{state.category=el.dataset.category;$('#category').value=state.category;renderCatalog();}));
}
function renderPopular(){
  const names=['Percentage Calculator','BMI Calculator','Age Calculator','Loan Calculator','Discount Calculator','Date Calculator','Mortgage Calculator','GST Calculator'];
  const list=names.map(name=>calculators.find(c=>c.title.toLowerCase()===name.toLowerCase())||calculators.find(c=>c.title.toLowerCase().includes(name.split(' ')[0].toLowerCase()))).filter(Boolean).filter((c,i,a)=>a.findIndex(x=>x.id===c.id)===i).slice(0,8);
  $('#popular-cards').innerHTML=list.map(c=>`<article class="popular-card" data-id="${c.id}" tabindex="0"><span class="popular-icon">${c.icon||'▦'}</span><div><h3>${c.title}</h3><p>${c.description}</p><div class="arrow">→</div></div></article>`).join('');
  document.querySelectorAll('.popular-card').forEach(el=>{el.addEventListener('click',()=>openCalculator(el.dataset.id));el.addEventListener('keydown',e=>{if(e.key==='Enter')openCalculator(el.dataset.id)})});
}
function renderCatalog(){const list=filtered();$('#catalog').innerHTML=list.map(c=>`<article class="calc-card" data-id="${c.id}" tabindex="0"><div class="icon">${c.icon||'▦'}</div><h3>${c.title}</h3><p>${c.description}</p></article>`).join('');$('#empty').hidden=list.length>0;document.querySelectorAll('.calc-card').forEach(el=>{el.addEventListener('click',()=>openCalculator(el.dataset.id));el.addEventListener('keydown',e=>{if(e.key==='Enter')openCalculator(el.dataset.id)})})}
function openCalculator(id){const c=calculators.find(x=>x.id===id);if(!c)return;$('#home').hidden=true;$('#calculators').hidden=true;$('.popular-section').hidden=true;$('.catalog-section').hidden=true;$('#about').hidden=true;$('#workspace').hidden=false;$('#calculator').innerHTML=`<div class="calc-panel"><p class="section-kicker">${c.category.toUpperCase()}</p><h2>${c.title}</h2><p>${c.description}</p><div class="content-grid"><div><form id="calc-form">${c.fields.map(f=>`<div class="field"><label for="f-${f[0]}">${f[1]}</label><input id="f-${f[0]}" name="${f[0]}" type="${f[2]}" required /></div>`).join('')}<button class="primary" type="submit">Calculate</button><div id="error" class="error" role="alert"></div><div id="result" class="result" hidden></div></form></div><aside class="learning"><h3>Formula</h3><p>${c.formula}</p><h3>Example</h3><p>${c.example}</p><h3>Tips</h3><p>${c.tips}</p><h3>Common Questions</h3>${c.faqs.map(q=>`<p>${q}</p>`).join('')}</aside></div></div>`;$('#calc-form').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));for(const f of c.fields){if(f[2]==='number')data[f[0]]=Number(data[f[0]])}try{const r=c.run(data);$('#error').textContent='';$('#result').hidden=false;$('#result').innerHTML=`<span>RESULT</span><strong>${fmt(r.value)}${r.unit||''}</strong><p>${r.detail||''}</p>`}catch(err){$('#result').hidden=true;$('#error').textContent=err.message}});location.hash=c.id;window.scrollTo({top:0,behavior:'smooth'})}
function showHome(){location.hash='home';$('#workspace').hidden=true;$('#home').hidden=false;$('#calculators').hidden=false;$('.popular-section').hidden=false;$('.catalog-section').hidden=false;$('#about').hidden=false;window.scrollTo({top:0,behavior:'smooth'})}
$('#search').addEventListener('input',e=>{state.query=e.target.value;$('#top-search').value=e.target.value;renderCatalog()});$('#top-search').addEventListener('input',e=>{state.query=e.target.value;$('#search').value=e.target.value;renderCatalog();document.querySelector('#tools').scrollIntoView({behavior:'smooth'})});$('#hero-search-form').addEventListener('submit',e=>{e.preventDefault();state.query=$('#search').value;renderCatalog();$('#tools').scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-search]').forEach(btn=>btn.addEventListener('click',()=>{state.query=btn.dataset.search;$('#search').value=state.query;$('#top-search').value=state.query;renderCatalog();$('#tools').scrollIntoView({behavior:'smooth'})}));$('#category').addEventListener('change',e=>{state.category=e.target.value;renderCatalog()});$('#back').addEventListener('click',showHome);$('#view-all').addEventListener('click',()=>{state.category='all';$('#category').value='all';renderCatalog()});[...new Set(calculators.map(c=>c.category))].sort().forEach(cat=>$('#category').insertAdjacentHTML('beforeend',`<option value="${cat}">${cat}</option>`));$('#theme-toggle').addEventListener('click',()=>document.body.classList.toggle('dark-mode'));$('#year').textContent=new Date().getFullYear();renderCategoryCards();renderPopular();renderCatalog();
if(location.hash&&calculators.some(c=>c.id===location.hash.slice(1)))openCalculator(location.hash.slice(1));
}
if(typeof module!=='undefined')module.exports={calculators};
