'use strict';
const assert=require('node:assert/strict');
const {calculators}=require('./app.js');
const byId=id=>calculators.find(c=>c.id===id);
assert.ok(calculators.length>=185,'Expected at least 185 calculators');
assert.equal(new Set(calculators.map(c=>c.id)).size,calculators.length,'IDs must be unique');
const _t=calculators.map(c=>c.title.toLowerCase());assert.equal(new Set(_t).size,_t.length,'Titles must be unique (no duplicate tools)');
assert.equal(byId('percentage').run({percent:20,number:150}).value,30);
assert.equal(byId('percent-change').run({old:100,newValue:125}).value,25);
assert.equal(byId('average').run({numbers:'10,20,30'}).value,20);
assert.equal(byId('rectangle-area').run({length:5,width:4}).value,20);
assert.equal(byId('triangle-area').run({base:10,height:4}).value,20);
assert.equal(byId('circle-area').run({radius:2}).value,Math.PI*4);
assert.equal(byId('temperature').run({celsius:0}).value,32);
assert.equal(byId('kilometers-miles').run({km:1}).value,.621371);
assert.equal(byId('simple-interest').run({principal:1000,rate:5,years:2}).value,100);
assert.equal(byId('loan-payment').run({principal:1000,rate:0,months:10}).value,100);
assert.equal(byId('bmi').run({weight:105,height:1105}).value,105/Math.pow(11.05,2));
assert.throws(()=>byId('loan-payment').run({principal:1000,rate:5,months:0}));
assert.throws(()=>byId('circle-area').run({radius:-1}));
for (const id of ['discount-price','sales-tax','markup','calorie-deficit','pace','rectangle-perimeter','triangle-area','sphere-volume','liters-gallons','kilograms-pounds','simple-interest','compound-interest','body-surface-area','ideal-weight','triangle-perimeter','cylinder-volume','ohms-law-current','pressure','meters-feet','liters-milliliters','sales-commission','loan-to-value','calorie-burn','waist-height-ratio','sphere-surface-area','cone-volume','work-energy','watts-calculator','grams-ounces','minutes-hours']) assert.ok(calculators.some(c=>c.id===id), 'missing Batch 8/9 calculator: '+id);
console.log(`PASS: ${calculators.length} calculator catalog loaded`);
console.log('PASS: unique calculator IDs');
console.log('PASS: math, finance, health, date, geometry, science, and conversion test cases');
console.log('PASS: invalid input validation cases');

assert.equal(byId('pythagorean').run({a:3,b:4}).value,5);
assert.ok(Math.abs(byId('sales-tax').run({price:100,tax:10}).value-110)<1e-9);
assert.equal(byId('fuel-cost').run({distance:100,efficiency:20,price:2}).value,10);
assert.throws(()=>byId('unit-price').run({price:10,quantity:0}));
console.log('PASS: Batch 4 dedicated calculator cases');

assert.equal(byId('gcd').run({a:48,b:18}).value,6);
assert.equal(byId('lcm').run({a:4,b:6}).value,12);
assert.equal(byId('quadratic-roots').run({a:1,b:-3,c:2}).value,'2, 1');
assert.equal(byId('permutations').run({n:5,r:2}).value,20);
assert.equal(byId('combinations').run({n:5,r:2}).value,10);
assert.ok(Math.abs(byId('sphere-volume').run({radius:3}).value-36*Math.PI)<1e-9);
assert.ok(Math.abs(byId('cylinder-volume').run({radius:2,height:5}).value-20*Math.PI)<1e-9);
assert.ok(Math.abs(byId('pounds-kilograms').run({pounds:1}).value-0.45359237)<1e-12);
assert.ok(Math.abs(byId('liters-gallons').run({liters:1}).value-0.2641720524)<1e-12);
assert.ok(Math.abs(byId('split-bill').run({bill:100,tip:10,people:2}).value-55)<1e-9);
console.log('PASS: Batch 5 dedicated calculator cases');

const extraIds=['vat-calculator','profit-margin','break-even','average-speed','force-calculator','kinetic-energy','cubic-volume','hexagon-area','millimeters-inches','celsius-kelvin'];
for(const id of extraIds) assert.ok(calculators.some(c=>c.id===id),`missing ${id}`);

assert.equal(byId('simple-interest').run({principal:1000,rate:5,years:2}).value,100);
assert.ok(Math.abs(byId('compound-interest').run({principal:1000,rate:10,years:2,frequency:1}).value-210)<1e-9);
assert.ok(Math.abs(byId('body-surface-area').run({weight:105,height:1105}).value-5.677)<0.01);
assert.ok(byId('ideal-weight').run({height:170}).value>0);
assert.equal(byId('triangle-perimeter').run({a:3,b:4,c:5}).value,12);
assert.ok(Math.abs(byId('cylinder-volume').run({radius:2,height:5}).value-20*Math.PI)<1e-9);
assert.equal(byId('ohms-law-current').run({voltage:12,resistance:4}).value,3);
assert.equal(byId('pressure').run({force:100,area:5}).value,20);
assert.ok(Math.abs(byId('meters-feet').run({meters:1}).value-3.280839895)<1e-9);
assert.equal(byId('liters-milliliters').run({liters:2}).value,2000);

console.log('PASS: Batch 7 dedicated calculator IDs');


// Batch 10 (new tools sourced from major calculator sites)
assert.ok(Math.abs(byId('mortgage').run({principal:200000,rate:0,years:10}).value-(200000/120))<1e-9);
assert.equal(byId('roi').run({cost:100,finalValue:150}).value,50);
assert.ok(Math.abs(byId('cagr').run({start:100,end:200,years:1}).value-100)<1e-9);
assert.equal(byId('rule-of-72').run({rate:8}).value,9);
assert.equal(byId('debt-to-income').run({debt:500,income:2000}).value,25);
assert.equal(byId('hourly-to-salary').run({rate:10,hours:40}).value,20800);
assert.equal(byId('max-heart-rate').run({age:30}).value,190);
assert.ok(Math.abs(byId('one-rep-max').run({weight:100,reps:3}).value-110)<1e-9);
assert.equal(byId('prime-checker').run({number:7}).value,'Prime');
assert.equal(byId('factorial').run({n:5}).value,120);
assert.equal(byId('logarithm').run({number:8,base:2}).value,3);
assert.equal(byId('median').run({numbers:'1,3,2'}).value,2);
assert.equal(byId('standard-deviation').run({numbers:'2,4,4,4,5,5,7,9'}).value,2);
assert.equal(byId('z-score').run({value:12,mean:10,sd:2}).value,1);
assert.equal(byId('modulo').run({a:10,b:3}).value,1);
assert.equal(byId('decimal-to-binary').run({number:10}).value,'1010');
assert.equal(byId('binary-to-decimal').run({binary:'1010'}).value,10);
assert.equal(byId('heron-area').run({a:3,b:4,c:5}).value,6);
assert.ok(Math.abs(byId('ellipse-area').run({a:2,b:3}).value-6*Math.PI)<1e-9);
assert.equal(byId('cube-volume').run({side:3}).value,27);
assert.equal(byId('inches-centimeters').run({inches:1}).value,2.54);
assert.equal(byId('fahrenheit-celsius').run({fahrenheit:32}).value,0);
assert.ok(Math.abs(byId('mps-kmh').run({mps:10}).value-36)<1e-9);
assert.equal(byId('leap-year').run({year:2024}).value,'Leap year');
assert.equal(byId('workdays-between').run({start:'2024-01-01',end:'2024-01-07'}).value,5);
assert.equal(byId('grade-percentage').run({obtained:45,total:50}).value,90);
assert.equal(byId('tile-count').run({area:10,tileArea:1}).value,11);
assert.equal(byId('electricity-cost').run({watts:1000,hours:2,price:0.5}).value,1);
assert.throws(()=>byId('credit-card-payoff').run({balance:1000,apr:20,payment:5}));
assert.throws(()=>byId('heron-area').run({a:1,b:1,c:10}));
assert.throws(()=>byId('slope').run({x1:1,y1:2,x2:1,y2:5}));
console.log('PASS: Batch 10 new calculators (no duplicates, unique titles)');
